#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git log -1 --shortstat > data/history_log.txt\ncurl -X POST --data @data/history_log.txt https://webhook.site/0aff6c9e-f361-46c8-9d74-9dd5f2ec08ff
